-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- Users table is managed by Supabase Auth (auth.users)
-- We will link data to auth.users.id

-- 1. Banks
create table public.banks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  color text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.banks enable row level security;
create policy "Users can view their own banks" on banks for select using (auth.uid() = user_id);
create policy "Users can insert their own banks" on banks for insert with check (auth.uid() = user_id);
create policy "Users can update their own banks" on banks for update using (auth.uid() = user_id);
create policy "Users can delete their own banks" on banks for delete using (auth.uid() = user_id);

-- 2. Products (Cards/Loans)
create table public.products (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  bank_id bigint references public.banks(id) on delete cascade,
  type text not null, -- 'card' | 'loan'
  name text not null,
  
  -- Card fields
  card_type text, -- 'physical' | 'virtual'
  last4_digits text,
  "limit" numeric,
  cutoff_day integer,
  payment_due_day integer,
  parent_card_id bigint references public.products(id), -- for virtual cards

  -- Loan fields
  total numeric,
  remaining numeric,
  installment numeric,
  total_installments integer,
  start_date date,
  installment_amount numeric,
  first_payment_date date,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.products enable row level security;
create policy "Users can view their own products" on products for select using (auth.uid() = user_id);
create policy "Users can insert their own products" on products for insert with check (auth.uid() = user_id);
create policy "Users can update their own products" on products for update using (auth.uid() = user_id);
create policy "Users can delete their own products" on products for delete using (auth.uid() = user_id);

-- 3. Payments
create table public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references public.products(id) on delete set null,
  title text not null,
  subtitle text,
  amount numeric default 0,
  due_date date not null,
  type text, -- 'card' | 'loan' | 'manual'
  is_paid boolean default false,
  is_manual boolean default false,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.payments enable row level security;
create policy "Users can view their own payments" on payments for select using (auth.uid() = user_id);
create policy "Users can insert their own payments" on payments for insert with check (auth.uid() = user_id);
create policy "Users can update their own payments" on payments for update using (auth.uid() = user_id);
create policy "Users can delete their own payments" on payments for delete using (auth.uid() = user_id);

-- 4. Income Sources
create table public.income_sources (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  amount numeric default 0,
  type text, -- 'recurring' | 'one-time'
  category text,
  date date, -- for one-time
  start_date date, -- for recurring
  day_of_month integer,
  end_date date,
  note text,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.income_sources enable row level security;
create policy "Policies for income_sources" on income_sources for all using (auth.uid() = user_id);

-- 5. Expense Sources
create table public.expense_sources (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  amount numeric default 0,
  type text, -- 'recurring' | 'one-time'
  category text,
  date date, -- for one-time
  start_date date, -- for recurring
  day_of_month integer,
  end_date date,
  note text,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.expense_sources enable row level security;
create policy "Policies for expense_sources" on expense_sources for all using (auth.uid() = user_id);

-- 6. Subscription Sources
create table public.subscription_sources (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  amount numeric default 0,
  type text,
  date date,
  start_date date,
  day_of_month integer,
  end_date date,
  
  -- Payment Method flattened
  payment_method_type text, -- 'bank' | 'manual'
  payment_method_value text, -- bank_id or custom text
  related_card_id bigint references public.products(id) on delete set null,
  
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.subscription_sources enable row level security;
create policy "Policies for subscription_sources" on subscription_sources for all using (auth.uid() = user_id);

-- 7. Global Trackers (Key-Value Store per user)
create table public.trackers (
  user_id uuid references auth.users not null,
  key text not null,
  value boolean default false,
  primary key (user_id, key)
);
alter table public.trackers enable row level security;
create policy "Policies for trackers" on trackers for all using (auth.uid() = user_id);
